spring.application.name=votethegoat
server.port=8000

# MongoDB
spring.data.mongodb.uri=mongodb+srv://p9897401_db_user:AiW5ILIP0QN3LjB4@sahild11.ekgaukq.mongodb.net/votingsystem?retryWrites=true&w=majority&appName=Sahild11&tls=true&tlsInsecure=true

# Email SMTP Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=p9897401@gmail.com
spring.mail.password=mloo fwvz pofe xayc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
